export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';

export const LOAD_FILES_SUCCESS = 'LOAD_FILE_SUCCESS';

export const LOAD_BREWERIES_SUCCESS = 'LOAD_BREWERIES_SUCCESS';
export const SAVE_BREWERIES_SUCCESS = 'SAVE_BREWERIES_SUCCESS';
export const DELETE_BREWERIES_SUCCESS = 'DELETE_BREWERIES_SUCCESS';

