export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_BREWERIES_SUCCESS = 'LOAD_BREWERIES_SUCCESS';
export const SAVE_BREWERIES_SUCCESS = 'SAVE_BREWERIES_SUCCESS';
export const DELETE_BREWERIES_SUCCESS = 'DELETE_BREWERIES_SUCCESS';
export const UPDATE_BREWERIES_SUCCESS = 'UPDATE_BREWERIES_SUCCESS';
export const LOAD_FILTERED_BREWERIES_SUCCESS = "LOAD_FILTERED_BREWERIES_SUCCESS";
